DROP TABLE IF EXISTS comments;

CREATE TABLE comments (
id SERIAL PRIMARY KEY,
username VARCHAR(200) NOT NULL,
comment TEXT not NULL,
comment_id INTEGER REFERENCES users(id) NOT NULL,
timeSent TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
